from selenium import webdriver

browser = webdriver.Chrome()
browser.get("http://pornhub.com")
browser = webdriver.Chrome()
browser.get("http://pornhub.com")
browser = webdriver.Chrome()
browser.get("http://pornhub.com")
browser = webdriver.Chrome()
browser.get("http://pornhub.com")
browser = webdriver.Chrome()
browser.get("http://pornhub.com")
browser = webdriver.Chrome()
browser.get("http://pornhub.com")
browser = webdriver.Chrome()
browser.get("http://pornhub.com")
browser = webdriver.Chrome()
browser.get("http://pornhub.com")
browser = webdriver.Chrome()
browser.get("http://pornhub.com")
browser = webdriver.Chrome()
browser.get("http://pornhub.com")
browser = webdriver.Chrome()
browser.get("http://pornhub.com")
browser = webdriver.Chrome()
browser.get("http://pornhub.com")
browser = webdriver.Chrome()
browser.get("http://pornhub.com")
browser = webdriver.Chrome()
browser.get("http://pornhub.com")
browser = webdriver.Chrome()
browser.get("http://pornhub.com")
browser = webdriver.Chrome()
browser.get("http://pornhub.com")
browser = webdriver.Chrome()
browser.get("http://pornhub.com")
browser = webdriver.Chrome()
browser.get("http://pornhub.com")
browser = webdriver.Chrome()
browser.get("http://pornhub.com")
browser = webdriver.Chrome()
browser.get("http://pornhub.com")
browser = webdriver.Chrome()
browser.get("http://pornhub.com")
browser = webdriver.Chrome()
browser.get("http://pornhub.com")
browser = webdriver.Chrome()
browser.get("http://pornhub.com")
browser = webdriver.Chrome()
browser.get("http://pornhub.com")